UserMetricTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: omni-live-logistics-user-metrics-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "user_id"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "user_id"
        KeyType: HASH