function:
  name: omni-live-logistics-establish-metrics-${self:provider.stage}
  handler: src/establish-metrics.handler
  description: omni live logistics establish metrics
  package:
    patterns:
      - "!**/*"
      - "src/establish-metrics.py"
  runtime: python3.7
  layers:
    - { Ref: OmniLiveLogisticsLambdaLayer }
  timeout: 300