function:
  name: omni-live-logistics-getdata-${self:provider.stage}
  handler: src/getdata.handler
  description: omni live logistics getdata
  package:
    patterns:
      - "!**/*"
      - "src/shared/**"
      - "src/getdata.py"
  runtime: python3.7
  layers:
    - { Ref: OmniLiveLogisticsLambdaLayer }
  timeout: 600
  # events:
  #   - schedule: cron(0 8 ? * MON-FRI *)
  events:
    - http:
        path: /getdata
        method: GET
        integration: lambda
        cors: true
        authorizer:
            arn: arn:aws:cognito-idp:us-east-1:332281781429:userpool/us-east-1_nH3rxLIdf
        
  environment:
    USER_METRICS_TABLE: ${ssm:/omni-live-logistics/${self:provider.stage}/user-metric/tableName~true}
    API_USERNAME: ${ssm:/omni-live-logistics/${self:provider.stage}/username~true}
    API_PASSWORD: ${ssm:/omni-live-logistics/${self:provider.stage}/password~true}
    API_URL: ${ssm:/omni-live-logistics/${self:provider.stage}/url~true}