function:
  name: omni-live-toggle-refact-${self:provider.stage}
  handler: src/toggle.handler
  description: omni live logistics update toggle
  package:
    patterns:
      - "!**/*"
      - "src/shared/**"
      - "src/toggle.py"
  runtime: python3.7
  # layers:
  #   - { Ref: OmniLiveLogisticsLambdaLayer }
  timeout: 600
  # events:
  #   - schedule: cron(0 8 ? * MON-FRI *)
  events:
    - http:
        path: /toggle
        method: POST
        authorizer:
            arn: ${ssm:/omni-rep-assignment/userpool}
        integration: lambda
        cors:
          origin: "*"
          headers:
            - Access-Control-Allow-Origin
            - X-Request-Id
            - Access-Control-Allow-Headers
            - Authorization
            - Content-Type
            - X-Amz-Date
            - X-Amz-Security-Token
            - X-Amz-User-Agent
            - X-Customer-Id
            - X-Api-Key 

  environment:
    USER_METRICS_TABLE: "omni-live-user-metrics-refact-dev"
    API_USERNAME: ${ssm:/omni-live-logistics/${self:provider.stage}/username~true}
    API_PASSWORD: ${ssm:/omni-live-logistics/${self:provider.stage}/password~true}
    API_URL: ${ssm:/omni-live-logistics/${self:provider.stage}/url~true}
    