function:
  name: omni-live-update-dispatcher-refact-${self:provider.stage}
  handler: src/update-dispatcher.handler
  description: omni live logistics update dispatcher
  package:
    patterns:
      - "!**/*"
      - "src/shared/**"
      - "src/update-dispatcher.py"
  runtime: python3.7
  layers:
    - { Ref: OmniLiveLogisticsLambdaLayer }
  events:
    - schedule: 
        rate: cron(0/5 * ? * * *)
        enabled: false
  environment:
    USER_METRICS_TABLE: "omni-live-user-metrics-refact-dev"
    API_USERNAME: ${ssm:/omni-live-logistics/${self:provider.stage}/username~true}
    API_PASSWORD: ${ssm:/omni-live-logistics/${self:provider.stage}/password~true}
    API_URL: ${ssm:/omni-live-logistics/${self:provider.stage}/url~true}